export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED';

export const GET_VIEWED_INGREDIENT = 'GET_VIEWED_INGREDIENT';
export const DEL_VIEWED_INGREDIENT = 'DEL_VIEWED_INGREDIENT';

export const ADD_INGREDIENT_CONSTRUCTOR = 'ADD_INGREDIENT_CONSTRUCTOR';
export const DEL_INGREDIENT_CONSTRUCTOR = 'DEL_INGREDIENT_CONSTRUCTOR'; 

export const INCREASE_INGREDIENTS = 'INCREASE_INGREDIENTS';
export const REDUCE_INGREDIENTS = 'REDUCE_INGREDIENTS'; 