export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_ERROR = 'GET_ITEMS_ERROR';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR = 'GET_ORDER_ERROR';

export const GET_VIEWED_INGREDIENT = 'GET_VIEWED_INGREDIENT';
export const DEL_VIEWED_INGREDIENT = 'DEL_VIEWED_INGREDIENT';

export const CLEAR_ORDER_NUMBER = 'CLEAR_ORDER_NUMBER';

export const ADD_INGREDIENT_CONSTRUCTOR = 'ADD_INGREDIENT_CONSTRUCTOR';
export const DEL_INGREDIENT_CONSTRUCTOR = 'DEL_INGREDIENT_CONSTRUCTOR';

export const INCREASE_INGREDIENTS = 'INCREASE_INGREDIENTS';
export const REDUCE_INGREDIENTS = 'REDUCE_INGREDIENTS';

export const DRAG_CONSTRUCTOR_INGREDIENT = 'DRAG_CONSTRUCTOR_INGREDIENT';

export const ORDER_DETAILS_OPEN = 'ORDER_DETAILS_OPEN';
export const INGREDIENT_DETAILS_OPEN = 'INGREDIENT_DETAILS_OPEN';
